services:
  - type: web
    name: animehub-22
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: COOKIE_SECURE
        value: "1"
